server:
  port: 8080
  servlet:
    context-path: /ankhang

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ankhang
    username: root
    password: tancoi123123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  signerKey: "pljZIkpjHqO2i+fBlMVuuNzO9WkeV0tTtyAcW8POBd2xV9GEmNlnHMRRCklIIiFm"

logging:
  level:
    org.springframework.security: DEBUG
