import { useEffect, useState } from "react";

const storeOriginCountries = [
  "Việt Nam",
  "Hoa Kỳ",
  "Pháp",
  "Nhật Bản",
  "Úc",
  "Anh",
  "Ý",
  "Ba Lan",
  "Đức",
  "Slovenia",
  "Thái Lan",
  "Canada",
  "New Zealand",
  "Hà Lan",
  "Hàn Quốc",
  "Monaco",
  "Tây Ban Nha",
  "Đan Mạch",
];
const storeBrands = [
  "Jpanwell",
  "Kingphar",
  "Thái Minh",
  "Vitamins For Life",
  "OMEXXEL",
  "Nam Dược",
  "Vitabiotics",
  "Abbott",
  "Ecogreen",
  "Á Âu",
  "Botania",
  "OCAVILL",
  "VITADAIRY",
  "Brauer",
  "KENKO",
  "Tuệ Linh",
];

const storeBlaBla = [
  [
    "Trẻ em",
    "Trẻ sơ sinh",
    "Phụ nữ có thai",
    "Phụ nữ sau sinh",
    "Phụ nữ",
    "Trẻ em",
    "Người lớn",
    "Người cao tuổi",
    "Người trưởng thành",
    "Phụ nữ có thai",
    "Phụ nữ cho con bú",
    "Phụ nữ chuẩn bị mang thai",
    "Phụ nữ sau sinh",
    "Người bị viêm loét dạ dày - tá tràng",
    "Nam giới trưởng thành",
    "Người có nhu cầu bổ sung calci",
    "Phụ nữ",
    "Trẻ sơ sinh",
    "Người bị mỡ Máu",
    "Người bị tiểu đường",
    "Người có nguy cơ hình thành cục máu đông",
    "Người sau tai biến mạch máu não do tắc mạch",
    "Người suy gan, thận",
    "Người thiểu năng tuần hoàn não",
    "Phụ nữ sảy thai",
    "Phụ nữ trong thời kỳ kinh nguyệt",
    "Phụ nữ tuổi tiền mãn kinh và mãn kinh",
    "Trẻ em",
    "Người bị tiểu đường",
    "Người bị suy tĩnh mạch",
    "Vận động viên",
    "Người bị trĩ",
    "Người cao tuổi",
    "Phụ nữ",
    "Qua phẫu thuật",
    "Người bị táo bón",
    "Phụ nữ có thai",
    "Phụ nữ sau sinh",
    "Trẻ sơ sinh",
    "Trẻ em",
    "Người lớn",
    "Người cao tuổi",
    "Người bị tiểu đường",
    "Người ăn kiêng",
    "Phụ nữ sau sinh",
    "Phụ nữ có thai",
    "Phụ nữ",
    "Phụ nữ cho con bú",
    "Trẻ sơ sinh",
    "Trẻ nhỏ",
    "Vận động viên",
  ],
  [
    "Rối loạn tiêu hóa",
    "Suy giảm hệ miễn dịch",
    "Mất ngủ",
    "Táo bón",
    "Cholesterol máu cao",
    "Lão hóa da",
    "Suy giảm trí nhớ",
    "Xơ vữa động mạch",
    "Biếng ăn",
    "Ho có đàm",
    "Suy nhược cơ thể",
    "Thoái hóa khớp",
    "Viêm họng",
    "Khó tiêu",
    "Mệt mỏi",
    "Rát họng",
    "Suy dinh dưỡng",
    "Bệnh tim mạch",
    "Vết thương ngoài da",
    "Nghẹt mũi",
    "Rách, đứt (da, tay, chân)",
    "Chấn thương",
    "Viêm mũi",
    "Viêm xoang",
    "Bong gân",
    "Cảm lạnh",
    "Đau chân",
    "Chuột rút co cứng",
    "Giãn tĩnh mạch",
    "Hôi miệng",
    "Sâu răng",
    "Bệnh lây truyền qua đường tình dục",
    "Hăm tã",
    "Rôm sảy",
    "Viêm lợi",
    "Cảm lạnh",
    "Ho khan",
    "Mụn nhọt",
    "Ngứa",
    "Nhiệt miệng",
    "Viêm nha chu",
    "Viêm nướu",
    "Đau họng",
    "Sẹo - Vết thâm",
    "Da khô - mất ẩm",
    "Ngứa",
    "Da dầu - da nhờn",
    "Mụn trứng cá",
    "Nứt nẻ",
    "Rôm sảy",
    "Hăm tã",
    "Mụn đầu đen",
    "Chàm",
    "Da khô",
    "Ngứa da",
    "Chống nắng",
    "Da đầu gàu / Nấm",
  ],
  [
    "Giảm đau",
    "Hạ sốt",
    "Vệ sinh mắt",
    "Vệ sinh tai",
    "Vệ sinh mũi",
    "Vệ sinh họng",
    "Tiêu hóa",
    "Đau nhức",
    "Hô hấp",
    "Vitamin",
    "Tuần hoàn máu",
    "Chăm sóc gan",
    "Chăm sóc da",
    "Chống nắng",
    "Dưỡng ẩm",
    "Trị mụn",
    "Trị sẹo",
    "Vitamin",
    "Dầu cá, Omega 3, DHA",
    "Vitamin C",
    "Vitamin D",
    "Bổ sung sắt & Axit Folic",
    "Sinh lý nam",
    "Sinh lý nữ",
    "Sức khỏe tình dục",
    "Cân bằng nội tiết tố",
    "Hỗ trợ mãn kinh",
    "Chăm sóc gan",
    "Tăng sức đề kháng, miễn dịch",
    "Bổ mắt, bảo vệ mắt",
    "Hỗ trợ trao đổi chất",
    "Giải rượu, cai rượu",
    "Cơ xương khớp",
    "Hô hấp, ho, xoang",
    "Thận, tiền liệt tuyến",
    "Hỗ trợ điều trị trĩ",
    "Hỗ trợ điều trị gout",
    "Hỗ trợ điều trị tiểu đường",
    "Hỗ trợ điều trị ung thư",
    "Tiêu hóa",
    "Dạ dày, tá tràng",
    "Táo bón",
    "Vi sinh - Probiotic",
    "Đại tràng",
    "Khó tiêu",
    "Bổ não, cải thiện trí nhớ",
    "Hỗ trợ giấc ngủ ngon",
    "Tuần hoàn máu",
    "Kiểm soát căng thẳng",
    "Hoạt huyết",
    "Da",
    "Hỗ trợ giảm cân",
    "Tóc",
    "Giảm cholesterol",
    "Huyết áp",
    "Suy giãn tỉnh mạch",
    "Sữa",
    "Dinh dưỡng trẻ em",
    "Dụng cụ vệ sinh mũi",
    "Kim các loại",
    "Máy massage",
    "Túi chườm",
    "Vớ ngăn tĩnh mạch",
    "Găng tay",
    "Đai lưng",
    "Dụng cụ vệ sinh tai",
    "Đai nẹp",
    "Máy xông khí dung",
    "Máy đo huyết áp",
    "Máy, que thử đường huyết",
    "Thử thai",
    "Nhiệt kế",
    "Kit Test Covid",
    "Máy đo SpO2",
    "Băng y tế",
    "Bông y tế",
    "Cồn, nước sát trùng, nước muối",
    "Chăm sóc vết thương",
    "Xịt giảm đau, kháng viêm",
    "Miếng dán giảm đau, hạ sốt",
    "Khẩu trang y tế",
    "Khẩu trang vải",
    "Sữa rửa mặt (Kem, gel, sữa)",
    "Kem chống nắng da mặt",
    "Dưỡng da mặt",
    "Mặt nạ",
    "Serum, Essence hoặc Ampoule",
    "Toner ( nước hoa hồng )/Lotion",
    "Tẩy tế bào chết",
    "Xịt khoáng",
    "Nước tẩy trang, dầu tẩy trang",
    "Sữa tắm, xà bông",
    "Chống nắng toàn thân",
    "Lăn khử mùi, xịt khử mùi",
    "Sữa dưỡng thể, kem dưỡng thể",
    "Trị nứt da",
    "Kem dưỡng da, tay chân",
    "Chăm sóc ngực",
    "Message",
    "Trị sẹo, mờ vết thâm",
    "Kem trị mụn, gel trị mụn",
    "Dưỡng da bị khô, thiếu ẩm",
    "Kem trị nám, tàn nhang, đốm nâu",
    "Viêm da cơ địa",
    "Da bị kích ứng",
    "Tái tạo, chống lão hóa da",
    "Da sạm, xỉn màu",
    "Dầu gội đầu xả",
    "Dầu gội trị nấm",
    "Dưỡng tóc, ủ tóc",
    "Đặc trị cho tóc",
    "Son môi",
    "Trang điểm mặt",
    "Trị quầng thâm, bọng mắt",
    "Xóa nếp nhăn vùng mắt",
    "Dưỡng da mắt",
    "Tinh dầu",
    "Dầu dừa",
    "Bao cao su",
    "Gel bôi trơn",
    "Nước Yến",
    "Kẹo cứng",
    "Nước uống không gas",
    "Đường ăn kiêng",
    "Trà thảo dược",
    "Kẹo dẻo",
    "Tổ Yến",
    "Dung dịch vệ sinh phụ nữ",
    "Vệ sinh tai",
    "Băng vệ sinh",
    "Nước rửa tay",
    "Kem đánh răng",
    "Bàn chải điện",
    "Chi nha khoa",
    "Chăm sóc răng",
    "Nước súc miệng",
    "Chống muỗi & côn trùng",
    "Đồ dùng cho bé",
    "Đồ dùng cho mẹ",
    "Khăn giấy, khăn ướt",
    "Tinh dầu massage",
    "Tinh dầu trị cảm",
    "Tinh dầu xông",
    "Dụng cụ tẩy lông",
    "Dụng cụ cạo râu",
  ],
  [
    "Vị Cam",
    "Vị chanh",
    "Vị Dâu",
    "Bạc hà",
    "Khuynh Diệp",
    "Vị Chuối",
    "Vị Socola",
    "Vị gừng",
    "Cần tây",
    "Hương cam",
    "Quýt",
    "Trái cây",
    "Táo quế",
    "Vani",
    "Vị chanh bạc hà",
    "Vị cherry",
    "Vị việt quất",
    "Vị Vanila",
    "Hương chanh",
    "Hương dưa hấu",
  ],
  [
    "Da khô",
    "Da nhạy cảm",
    "Da mụn",
    "Mọi loại da",
    "Da dầu",
    "Da nhờn",
    "Da khô - mất ẩm",
    "Viêm da cơ địa",
    "Da thường",
    "Da hỗn hợp",
    "Sẹo - Vết thâm",
    "Da trang điểm",
    "Nám sạm",
    "Tàn nhang",
    "Đốm nâu",
    "Mọi loại da",
  ],
];
const getRandomNumber = (min: number, max: number): number => {
  return Math.floor(Math.random() * (max - min + 1)) + min;
};
const check = localStorage.getItem("indexIMG");
if (check == null) {
  localStorage.setItem("indexIMG", JSON.stringify(79.5));
}
export default function TempTest() {
  const [storeAll, setStoreAll] = useState<Set<string>[]>([
    new Set(),
    new Set(),
    new Set(),
    new Set(),
    new Set(),
  ]);

  useEffect(() => {
    const indexIMG = JSON.parse(localStorage.getItem("indexIMG") || "80");
    const tempStoreAll = [...storeAll];
    for (let i = 0; i < 5; i++) {
      const size = getRandomNumber(2, 5);

      for (let j = 0; j < size; j++) {
        tempStoreAll[i] = new Set(
          tempStoreAll[i].add(
            storeBlaBla[i][getRandomNumber(0, storeBlaBla[i].length - 1)]
          )
        );
      }
    }
    localStorage.setItem("indexIMG", indexIMG + 0.5);
    setStoreAll(tempStoreAll);
  }, []);
  return (
    <>
      <div>
        "imgURL":
        {`"medicine${JSON.parse(
          localStorage.getItem("indexIMG") || "80"
        )}.png"`}
        ,
      </div>
      <div>
        "targetPatience":
        {`[${[...storeAll[0]].map((each) => `"${each}"`).join(", ")}]`},
      </div>
      <div>
        "indications":{" "}
        {`[${[...storeAll[1]].map((each) => `"${each}"`).join(", ")}]`},
      </div>
      <div>
        "categories":{" "}
        {`[${[...storeAll[2]].map((each) => `"${each}"`).join(", ")}]`},
      </div>
      <div>
        "flavorOrScents":{" "}
        {`[${[...storeAll[3]].map((each) => `"${each}"`).join(", ")}]`},
      </div>
      <div>
        "skinTypes":{" "}
        {`[${[...storeAll[4]].map((each) => `"${each}"`).join(", ")}]`},
      </div>
      <div>
        "brand": "{storeBrands[getRandomNumber(0, storeBrands.length - 1)]}",
      </div>
      <div>
        "originCountry":"
        {
          storeOriginCountries[
            getRandomNumber(0, storeOriginCountries.length - 1)
          ]
        }
        "
      </div>
    </>
  );
}
